version: 3.7

volumes: 
    docs_node_modules:

services:
  dev:
    container_name: myproject_docs_dev
    build:
      dockerfile: Dockerfile.docs
      context: .
    image: myproject_docs
    working_dir: /root/workspace/docs
    volumes: 
      - ./docs:/root/workspace/docs
      - docs_node_modules:/root/workspace/docs/node_modules
    tty: true
    command: yarn start
    network_mode: host

  deploy:
    container_name: myproject_docs_deploy
    image: myproject_docs
    volumes: 
      - docs_node_modules:/root/workspace/docs/node_modules
      - ./docs:/root/workspace/docs
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
    working_dir: /root/workspace/docs
    command: yarn deploy

